CasanovaExchange/Controllers/TradeController.cs
using CasanovaExchange.Models;
using CasanovaExchange.Repository;
using CasanovaExchange.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace CasanovaExchange.Controllers
{
    public class TradeController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ICommodityRepository _commodityRepository;
        public TradeController(UserManager<IdentityUser> userManager, ICommodityRepository commodityRepository)
        {
            _userManager = userManager;
            _commodityRepository = commodityRepository;
        }
        // GET: Trade
        public ActionResult Index()
        {
            return View();
        }

        // GET: Trade/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BuyProduct(int id, IFormCollection collection)
        {
            try
            {

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult ListWarehouses()
        {
            List<Warehouse> warehouses = _commodityRepository.GetWarehouseList();
            return View(warehouses);
        }
        public ActionResult ListCommodities()
        {
            ViewBag.commodityLs = _commodityRepository.GetCommodityList();
            _commodityRepository.CheckPortfolio(_userManager.GetUserId(User));
            return View();
        }
        public ViewResult GetCommodity(string commodityString)
        {
            if (commodityString.IsNullOrEmpty())
                commodityString = "empty";
            ViewBag.Commodity = commodityString;
            List<Commodity> CommodityList = _commodityRepository.GetCommodityByName(commodityString);
            return View(CommodityList);
        }
        public ViewResult GetCommodityListings(int commodityId)
        {
            CommodityListingViewModel commodityListingViewModel = new()
            {
                commodity = _commodityRepository.GetCommodityById(commodityId)
            };
           
            commodityListingViewModel.CommodityListings = _commodityRepository.GetCommodityListings(commodityListingViewModel.commodity);
            commodityListingViewModel.CommodityListing = new CommodityListing()
            {
                Commodity = _commodityRepository.GetCommodityById(commodityId),
                Quantity = 0,
                Price = 0,
                Active = false
            };
            return View(commodityListingViewModel);
        }
        [HttpPost]
        public ViewResult BuyCommodity(CommodityListingViewModel commodityListingViewModel)
        {
            _commodityRepository.BuyCommodity(commodityListingViewModel, _userManager.GetUserId(User));
            return View(commodityListingViewModel);
        }
        [HttpPost]
        public ActionResult SellCommodity(CommodityListingViewModel commodityListingViewModel)
        {
            _commodityRepository.SellCommodity(commodityListingViewModel, _userManager.GetUserId(User));

            return RedirectToAction("Index", "Home");
        }
    }
}

CasanovaExchange/Controllers/WalletController.cs
using CasanovaExchange.Models;
using CasanovaExchange.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CasanovaExchange.Controllers
{
	public class WalletController : Controller
	{
		private readonly UserManager<IdentityUser> _userManager;
		private readonly ICommodityRepository _commodityRepository;
		public WalletController(UserManager<IdentityUser> userManager, ICommodityRepository commodityRepository)
		{
			_userManager = userManager;
			_commodityRepository = commodityRepository;
		}
		public IActionResult Index()
		{
			Wallet wallet = _commodityRepository.GetWallet(_userManager.GetUserId(User));
			return View(wallet);
		}
		[HttpPost]
		public IActionResult AddMoney(Wallet addBalance)
		{
			if (addBalance.Balance > 0)
			{
				_commodityRepository.AddBalance(_userManager.GetUserId(User), addBalance.Balance);
			}
			return RedirectToAction("Index");
		}
	}
}

CasanovaExchange/Views/Shared/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.OptionsIOptions<Microsoft.AspNetCore.Biulder.RequestLocalizationOptions> localOptions
    @{
    var culture = Context.Feature.Get<Microsoft.AspNetCore.Localization.IRequestCulture Feature>();
    var cultureList = localOption.Value.SupportedUICultures.Select(x => new SelectListItem {Value = x.Name , Text = localizer.Getstring(x.Name) }).ToList();
    var returnUrl = string.IsNullorWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Vlue}{Context.Request.QueryString}";
    }
<div>
    <form asp-action="CultureManagement" asp-controller="Home" method="post"
        asp-route-returnUrl="@returnUrl">
        <select name="culture" asp-for="@culure.RequestCulture.UICulture.Name" asp-item="cultureList">
        onchange="this.form.submit();"</select>
    </form>
</div>

CasanovaExchange/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CasanovaExchange</title>

	<link rel="shortcut icon" type="image/jpg" href="~/icons/coffee.png" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/CasanovaExchange.styles.css" asp-append-version="true" />

</head>
<body>
	<div class="body-container d-flex bg-dark">
		<div class="sidebar d-flex flex-column flex-shrink-0 p-3 text-white">
			<a asp-area="" asp-controller="Home" asp-action="Index" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">

				<span class="fs-4">Casanova Exchange</span>
			</a>


			<!--this is the place authenticated users only display the sidebar-->
			@if (User.Identity.IsAuthenticated)
			{
				@if (!User.IsInRole("Admin"))
				{
					<hr>
					<ul class="nav nav-pills flex-column mb-auto">
						<li>
							<a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-white">
								<img src="~/icons/icons8_Circle_Chart_128px.png" style="width: 30px;" />
								Portfolio
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Trade" asp-action="ListCommodities" class="nav-link text-white">
								<img class="flex-row align-items-center" src="~/icons/icons8_bullish_trade_128px.png" style="width: 30px;" />
								Trade
							</a>
						</li>
						<li>
							<a asp-controller="Wallet" asp-action="Index" class="nav-link text-white">
								<img class="flex-row align-items-center" src="~/icons/icons8_coin_wallet_64px.png" style="width: 30px;" />
								Wallet
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Home" asp-action="Privacy" class="nav-link text-white">
								<img class="flex-row align-items-center" src="~/icons/icons8_shield_64px.png" style="width: 30px;" />
								Privacy
							</a>
						</li>
					</ul>
					<hr>

					<div class="dropdown">
						<a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
							<img src="~/profile/userProfile.png" alt="" width="32" height="32" class="rounded-circle me-2">
							<strong>@User.Identity.Name</strong>
						</a>
						<ul class="dropdown-menu dropdown-menu-dark text-small shadow">
							<li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Setting">Settings</a></li>
							<li><hr class="dropdown-divider"></li>
							<li>
								<form class="" asp-area="" asp-controller="Account" asp-action="Logout">
									<button class="btn " style="color:whitesmoke"> Logout</button>
								</form>

							</li>
						</ul>
					</div>
				}
				else
				{

					<ul class="nav nav-pills flex-column mb-auto">
						<li>
							<a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-white">
								<img src="~/icons/icons8-home-50.png" style="width: 30px;" />
								Home
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Admin" asp-action="Warehouse" class="nav-link text-white">
								<img src="~/icons/icons8_Circle_Chart_128px.png" style="width: 30px;" />
								Warehouse
							</a>
						</li>
						<li>
							<a asp-area="" asp-controller="Admin" asp-action="Commodity" class="nav-link text-white">
								<img class="flex-row align-items-center" src="~/icons/icons8_bullish_trade_128px.png" style="width: 30px;" />
								Commodity
							</a>
						</li>
						</ul>

					<div class="dropdown">
						<a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
							<img src="~/profile/userProfile.png" alt="" width="32" height="32" class="rounded-circle me-2">
							<strong>@User.Identity.Name</strong>
						</a>
						<ul class="dropdown-menu dropdown-menu-dark text-small shadow">
							<li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Setting">Settings</a></li>
							<li><hr class="dropdown-divider"></li>
							<li>
								<form class="" asp-area="" asp-controller="Account" asp-action="Logout">
									<button class="btn " style="color:whitesmoke"> Logout</button>
								</form>

							</li>
						</ul>
					</div>
				}


			}
			else
			{
				<hr />
				<div class="form-group-bar">
					<a class="btn btn-outline-danger" asp-area="" asp-controller="Account" asp-action="Signin"> Sign In</a>
					<a class="btn btn-primary " asp-area="" asp-controller="Account" asp-action="SignUp"> Sign Up</a>


				</div>

			}

		</div>


		<div class="container overflow-y-scroll text-bg-dark text-white bg-dark">
			<main role="main" class="pb-3">
				@RenderBody()
			</main>
		</div>

	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>